<a href="https://colab.research.google.com/github/true-cpu/ThucHanhDeepLearning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Thực hành NumPy

In [9]:
import numpy as np

array_1d = np.arange(10)
print("Mảng 1D:\n", array_1d)

array_2d = np.arange(9).reshape(3, 3)
print("\nMảng 2D (3x3):\n", array_2d)

array_1d_resized = np.arange(9).reshape(3, 3)
sum_array = array_1d_resized + array_2d
print("\nPhép cộng mảng (1D_đã_thay_đổi_kích_thước (3x3) + 2D (3x3)):\n", sum_array)

scalar_multiplication = array_2d * 2
print("\nPhép nhân vô hướng (Mảng 2D * 2):\n", scalar_multiplication)

reshaped_array = array_1d.reshape(2, 5)
print("\nMảng 1D được định hình lại (thành 2x5):\n", reshaped_array)

print("\nTổng hợp trên Mảng 2D:")
print("Tổng của Mảng 2D:", array_2d.sum())
print("Trung bình của Mảng 2D:", array_2d.mean())
print("Giá trị lớn nhất của Mảng 2D:", array_2d.max())
print("Giá trị nhỏ nhất của Mảng 2D:", array_2d.min())

Mảng 1D:
 [0 1 2 3 4 5 6 7 8 9]

Mảng 2D (3x3):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Phép cộng mảng (1D_đã_thay_đổi_kích_thước (3x3) + 2D (3x3)):
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Phép nhân vô hướng (Mảng 2D * 2):
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Mảng 1D được định hình lại (thành 2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Tổng hợp trên Mảng 2D:
Tổng của Mảng 2D: 36
Trung bình của Mảng 2D: 4.0
Giá trị lớn nhất của Mảng 2D: 8
Giá trị nhỏ nhất của Mảng 2D: 0


In [10]:
print("\n--- Lập chỉ mục và cắt mảng NumPy ---")

print("\n1. Phần tử cụ thể từ mảng 1D (chỉ mục 4):")
print(array_1d[4])

print("\n2. Phần tử cụ thể từ mảng 2D (hàng 1, cột 2):")
print(array_2d[1, 2])

print("\n3. Mảng 1D đã cắt (chỉ mục 2 đến 7):")
print(array_1d[2:8])

print("\n4. Hàng cụ thể từ mảng 2D (hàng 1):")
print(array_2d[1, :])

# 5. Cắt array_2d để lấy một cột cụ thể (ví dụ: cột thứ ba - chỉ mục 2)
print("\n5. Cột cụ thể từ mảng 2D (cột 2):")
print(array_2d[:, 2])

# 6. Cắt array_2d để lấy một mảng con (ví dụ: hàng 0 đến 1, cột 1 đến 2)
print("\n6. Mảng con từ mảng 2D (hàng 0-1, cột 1-2):")
print(array_2d[0:2, 1:3])


--- Lập chỉ mục và cắt mảng NumPy ---

1. Phần tử cụ thể từ mảng 1D (chỉ mục 4):
4

2. Phần tử cụ thể từ mảng 2D (hàng 1, cột 2):
5

3. Mảng 1D đã cắt (chỉ mục 2 đến 7):
[2 3 4 5 6 7]

4. Hàng cụ thể từ mảng 2D (hàng 1):
[3 4 5]

5. Cột cụ thể từ mảng 2D (cột 2):
[2 5 8]

6. Mảng con từ mảng 2D (hàng 0-1, cột 1-2):
[[1 2]
 [4 5]]


### Thực hành Pandas

In [11]:
import pandas as pd

# Tạo một DataFrame Pandas từ dictionary 'data'
pd_dataframe = pd.DataFrame(data)
print("Đã tạo DataFrame từ dictionary 'data':")
print(pd_dataframe)

# Hiển thị 5 hàng đầu tiên của DataFrame
print("\n5 hàng đầu tiên của DataFrame:")
print(pd_dataframe.head())

# Hiển thị thông tin tóm tắt về DataFrame
print("\nThông tin DataFrame:")
pd_dataframe.info()

# Hiển thị thống kê mô tả của các cột số
print("\nThống kê mô tả:")
print(pd_dataframe.describe())

Đã tạo DataFrame từ dictionary 'data':
       Tên  Tuổi    Thành phố
0    Alice    24     New York
1      Bob    27  Los Angeles
2  Charlie    22      Chicago
3    David    32      Houston

5 hàng đầu tiên của DataFrame:
       Tên  Tuổi    Thành phố
0    Alice    24     New York
1      Bob    27  Los Angeles
2  Charlie    22      Chicago
3    David    32      Houston

Thông tin DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Tên        4 non-null      object
 1   Tuổi       4 non-null      int64 
 2   Thành phố  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Thống kê mô tả:
            Tuổi
count   4.000000
mean   26.250000
std     4.349329
min    22.000000
25%    23.500000
50%    25.500000
75%    28.250000
max    32.000000


In [12]:
print("\n--- Chọn và lọc dữ liệu Pandas ---")

# 1. Chọn cột 'Tên' từ DataFrame pd_dataframe
print("\n1. Chọn cột 'Tên':")
print(pd_dataframe['Tên'])

# 2. Sử dụng iloc để chọn hàng đầu tiên và tất cả các cột
print("\n2. Chọn hàng đầu tiên bằng iloc:")
print(pd_dataframe.iloc[0])

# 3. Sử dụng iloc để chọn hàng thứ hai (chỉ mục 1) và cột 'Tuổi' (chỉ mục 1)
print("\n3. Chọn phần tử ở hàng 1, cột 'Tuổi' bằng iloc:")
print(pd_dataframe.iloc[1, 1])

# 4. Sử dụng loc để chọn hàng có nhãn chỉ mục 0 và tất cả các cột
print("\n4. Chọn hàng có nhãn 0 bằng loc:")
print(pd_dataframe.loc[0])

# 5. Sử dụng loc để chọn hàng có nhãn chỉ mục 1 và cột 'Thành phố'
print("\n5. Chọn phần tử ở hàng 1, cột 'Thành phố' bằng loc:")
print(pd_dataframe.loc[1, 'Thành phố'])

# 6. Lọc pd_dataframe để lấy ra tất cả các hàng mà 'Tuổi' lớn hơn 25
filtered_data = pd_dataframe[pd_dataframe['Tuổi'] > 25]
print("\n6. Lọc DataFrame nơi 'Tuổi' > 25:")
print(filtered_data)


--- Chọn và lọc dữ liệu Pandas ---

1. Chọn cột 'Tên':
0      Alice
1        Bob
2    Charlie
3      David
Name: Tên, dtype: object

2. Chọn hàng đầu tiên bằng iloc:
Tên             Alice
Tuổi               24
Thành phố    New York
Name: 0, dtype: object

3. Chọn phần tử ở hàng 1, cột 'Tuổi' bằng iloc:
27

4. Chọn hàng có nhãn 0 bằng loc:
Tên             Alice
Tuổi               24
Thành phố    New York
Name: 0, dtype: object

5. Chọn phần tử ở hàng 1, cột 'Thành phố' bằng loc:
Los Angeles

6. Lọc DataFrame nơi 'Tuổi' > 25:
     Tên  Tuổi    Thành phố
1    Bob    27  Los Angeles
3  David    32      Houston


In [13]:
print("\n--- Thao tác dữ liệu Pandas ---")

# 1. Thêm một cột mới 'Năm sinh' vào pd_dataframe. Giả sử năm hiện tại là 2024.
pd_dataframe['Năm sinh'] = 2024 - pd_dataframe['Tuổi']
print("\n1. DataFrame sau khi thêm cột 'Năm sinh':")
print(pd_dataframe)

# 2. Sửa đổi cột 'Tuổi' hiện có bằng cách thêm 1 vào mỗi giá trị tuổi.
pd_dataframe['Tuổi'] = pd_dataframe['Tuổi'] + 1
print("\n2. DataFrame sau khi sửa đổi cột 'Tuổi' (đã thêm 1 vào mỗi giá trị):")
print(pd_dataframe)

# 3. Để minh họa việc xử lý giá trị thiếu, tạo một bản sao, thêm NaN, sau đó điền giá trị thiếu.
df_with_nan = pd_dataframe.copy()
df_with_nan.loc[1, 'Thành phố'] = None # hoặc np.nan
print("\n3a. DataFrame với một giá trị thiếu trong 'Thành phố' (để minh họa):")
print(df_with_nan)

df_filled = df_with_nan.fillna({'Thành phố': 'Không rõ'})
print("\n3b. DataFrame sau khi điền giá trị 'Thành phố' thiếu bằng 'Không rõ':")
print(df_filled)

# 4. Tạo một cột mới 'Giới tính' trong pd_dataframe với dữ liệu mẫu.
pd_dataframe['Giới tính'] = ['Nam', 'Nữ', 'Nam', 'Nữ']
print("\n4. DataFrame sau khi thêm cột 'Giới tính':")
print(pd_dataframe)

# 5. Nhóm pd_dataframe theo cột 'Giới tính' và tính tuổi trung bình cho mỗi nhóm.
grouped_by_gender = pd_dataframe.groupby('Giới tính')['Tuổi'].mean()
print("\n5. 'Tuổi' trung bình được nhóm theo 'Giới tính':")
print(grouped_by_gender)


--- Thao tác dữ liệu Pandas ---

1. DataFrame sau khi thêm cột 'Năm sinh':
       Tên  Tuổi    Thành phố  Năm sinh
0    Alice    24     New York      2000
1      Bob    27  Los Angeles      1997
2  Charlie    22      Chicago      2002
3    David    32      Houston      1992

2. DataFrame sau khi sửa đổi cột 'Tuổi' (đã thêm 1 vào mỗi giá trị):
       Tên  Tuổi    Thành phố  Năm sinh
0    Alice    25     New York      2000
1      Bob    28  Los Angeles      1997
2  Charlie    23      Chicago      2002
3    David    33      Houston      1992

3a. DataFrame với một giá trị thiếu trong 'Thành phố' (để minh họa):
       Tên  Tuổi Thành phố  Năm sinh
0    Alice    25  New York      2000
1      Bob    28      None      1997
2  Charlie    23   Chicago      2002
3    David    33   Houston      1992

3b. DataFrame sau khi điền giá trị 'Thành phố' thiếu bằng 'Không rõ':
       Tên  Tuổi Thành phố  Năm sinh
0    Alice    25  New York      2000
1      Bob    28  Không rõ      1997
2  Charlie    23 

Thực hành TensorFLow

In [20]:
import tensorflow as ts

rank_0_ts  = ts.constant(4)
print("Tensor có rank 0:", rank_0_ts)

r1 = ts.constant(9,ts.int16)
print("\nTensor có rank 1:", r1)

r1_float = ts.cast(r1, dtype=ts.float32)
print("\nTensor có rank 1 (float):", r1_float)

r1_string = ts.constant("Xin chào TensorFlow")
print("\nTensor có rank 1 (string):", r1_string)

rank1_ts = ts.constant([2.0, 3.0, 4.0])
print("\nTensor có rank 1:", rank1_ts)

rank2_ts = ts.constant([[1, 2],
                      [3, 4],
                      [5, 6]], dtype=ts.float16)
print("\nTensor có rank 2:", rank2_ts)

rank3_ts = ts.constant([[[0,1,2,3,4],[5,6,7,8,9]],
                      [[10,11,12,13,14],[15,16,17,18,19]],
                      [[20,21,22,23,24],[25,26,27,28,29]]])
print("\nTensor có rank 3:", rank3_ts)

Tensor có rank 0: tf.Tensor(4, shape=(), dtype=int32)

Tensor có rank 1: tf.Tensor(9, shape=(), dtype=int16)

Tensor có rank 1 (float): tf.Tensor(9.0, shape=(), dtype=float32)

Tensor có rank 1 (string): tf.Tensor(b'Xin ch\xc3\xa0o TensorFlow', shape=(), dtype=string)

Tensor có rank 1: tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)

Tensor có rank 2: tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)

Tensor có rank 3: tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
